### ISSUE TITLE
TXT cannot be Created

### ISSUE THREAD

**Issue by Nanboy-Ronan** [jbrightuniverse/Manual-Grading-Autocompiler#3]
Generated txt only contain name but no content.

**Comment by jbrightuniverse** [comment]
@Nanboy-Ronan this usually happens when there are no submission files in the assignment grading folder where you are running the program. Are the other submissions being compiled properly/is everything named exactly as in the instructions?

**Comment by Nanboy-Ronan** [comment]
Thanks for your fast reply. I should have followed all instructions and double checked that there are files in the AssignmentX folder. The tree is like root(autocompile)->AX->rubric and Assignment.

**Comment by jbrightuniverse** [comment]
Since you mentioned you have txt file, I assume you have the AX-to-grade subfolder generated? When you open the folder that has the generated txt, there should be a collection of subfolders named after either students or groups. Inside each folder should be the submission by the student. Are those present?

If not, it could be the case that the manual grading CSV file did not specify those files needed to be manually graded, but that is just a guess. Note that you can also debug by printing out the folder structure `print(os.listdir(pathname))` at around this line: https://github.com/jbrightuniverse/Manual-Grading-Autocompiler/blob/00598ff69904cc9c638af59547e2ee49d508dc2f/autocompile.py#L152 which is where the txts are generated.

**Comment by Nanboy-Ronan** [comment]
Yes, there is AX-to-grade subfolder. There are subfolders named students or groups. But inside that folder, there is no such submission files.  I just debugged it using PDB and find line 145 never evaluated to be true, thus no copyfile gets execuated.
(https://github.com/jbrightuniverse/Manual-Grading-Autocompiler/blob/00598ff69904cc9c638af59547e2ee49d508dc2f/autocompile.py#L145).

**Comment by jbrightuniverse** [comment]
That means the students from the CSV were not detected in the folder setup. To debug this, determine the contents of the:
https://github.com/jbrightuniverse/Manual-Grading-Autocompiler/blob/00598ff69904cc9c638af59547e2ee49d508dc2f/autocompile.py#L136
and compare this to the contents of the:
https://github.com/jbrightuniverse/Manual-Grading-Autocompiler/blob/00598ff69904cc9c638af59547e2ee49d508dc2f/autocompile.py#L143
It could be that there is a formatting mismatch/something changed in how names are recorded.

**Comment by Nanboy-Ronan** [comment]
https://github.com/jbrightuniverse/Manual-Grading-Autocompiler/blob/00598ff69904cc9c638af59547e2ee49d508dc2f/autocompile.py#L145
row[0] is cwl@ubc.ca while the LHS of the equation is cwl@ubc.ca.__IK7X... I suppose there is a UUID after .ubc.ca.

**Comment by jbrightuniverse** [comment]
Are there actually two `_` characters in order as you typed above? That might be the culprit. In any case, the fix is to adjust the foldername-cleaning code to more precisely extract the UID/groupname (I'll work on this tonight).

**Comment by Nanboy-Ronan** [comment]
> Are there actually two _ characters in order as you typed above? That might be the culprit. In any case, the fix is to adjust the foldername-cleaning code to more precisely extract the UID/groupname (I'll work on this tonight).

Sorry, it should only contain one '_'.
Copied from debugger: 'cwl@ubc.ca_IK7XMZAQLR09_a1'.

**Comment by jbrightuniverse** [comment]
By any chance do you have `gradeAllSubmissions` set to True? 
More specifically, what is the value of `amount_to_remove`? If it is nonzero, there should be a difference between `foldername` and `"_".join(foldername.split("_")[:-amount_to_remove])`

**Comment by Nanboy-Ronan** [comment]
> By any chance do you have `gradeAllSubmissions` set to True? More specifically, what is the value of `amount_to_remove`? If it is nonzero, there should be a difference between `foldername` and `"_".join(foldername.split("_")[:-amount_to_remove])`

GradeAllSubmissions is False.
amount_to_remove = 1.
By the way, could we have a zoom/video meeting, so that you can look into it more conveniently.

**Comment by jbrightuniverse** [comment]
@Nanboy-Ronan Actually I found the problem. It seems there are actually two underscores in the text itself:
![image](https://user-images.githubusercontent.com/30967260/152114375-068656b7-80a3-4e51-9cd7-3ae3b25251ca.png)
Will alter this in the code and it should work after that.
